services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: myapp-postgres-pgvector
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  message_parsing:
    build:
      context: ./message_parsing
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env


volumes:
  postgres_data: