name: assistant-api-ci

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'ai_assistants_api/**'
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID_GITHUB_AUTH }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name ${{ vars.ACR_NAME }}

      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
           context: ./ai_assistants_api
           push: true
           tags: ${{ vars.ACR_NAME }}/assistant-api:${{ github.sha }}